# SPDX-License-Identifier: Apache-2.0
[package]
name = "govfuzz_cc_intercept"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[package.metadata.dist]
dist = true
package-libraries = ["cdylib"]
install-libraries = ["cdylib"]

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
