# SPDX-License-Identifier: Apache-2.0

[package]
name = "idl_parser"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "idl_parser"
path = "src/main.rs"

[dev-dependencies]
ada_parser = { path = "../ada_parser" }
