# SPDX-License-Identifier: Apache-2.0

[package]
name = "fuzz_engine_builtin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ada_parser = { path = "../../ada_parser" }
cmplog = { path = "../../cmplog" }
event_log = { path = "../../event_log" }

[dev-dependencies]
serde_json.workspace = true

[[bin]]
name = "fuzz_engine_builtin"
path = "src/main.rs"
