// SPDX-License-Identifier: Apache-2.0

//! Generate the Alire "configuration" package (`<crate>_config.ads`) that `alr`
//! materializes from a crate's `alire.toml` `[configuration.variables]`.
//!
//! Alire crates expose build-time configuration as a generated package: source
//! does `with Usb_Embedded_Config; ... X : constant := Usb_Embedded_Config.
//! Control_Buffer_Size;`. The package only exists after `alr build` runs, so
//! without `alr` govfuzz can't compile any unit that depends on it ("missing Ada
//! symbol 'usb_embedded_config.String_Buffer_Size'"). The format is fixed and
//! the values are the declared defaults, so govfuzz can generate a faithful copy
//! deterministically — no `alr`, no network — and drop it on the build path.

use std::path::Path;

/// A generated Alire config package ready to write into the build source set.
#[derive(Debug, Clone, PartialEq)]
pub struct ConfigPackage {
    /// GNAT default file name, lowercase (`usb_embedded_config.ads`).
    pub file_name: String,
    /// Full Ada spec source.
    pub source: String,
}

/// Generate `<crate>_config.ads` from `alire_toml` if it declares
/// `[configuration.variables]`. Returns `None` when the file can't be read, has
/// no `name`, or declares no configuration variables (nothing to generate).
pub fn generate_config_package(alire_toml: &Path) -> Option<ConfigPackage> {
    let text = std::fs::read_to_string(alire_toml).ok()?;
    let crate_name = toml_string_field(&text, "name")?;
    let vars = parse_config_variables(&text);
    if vars.is_empty() {
        return None;
    }
    let pkg = ada_config_package_name(&crate_name);
    let mut body = String::new();
    body.push_str("--  SPDX-License-Identifier: Apache-2.0\n");
    body.push_str("--  Generated by govfuzz from alire.toml [configuration.variables]\n");
    body.push_str("--  (a faithful stand-in for the package `alr` would generate).\n");
    body.push_str(&format!("package {pkg} is\n"));
    body.push_str(&format!(
        "   Crate_Version : constant String := \"0.0.0\";\n   Crate_Name : constant String := \"{crate_name}\";\n"
    ));
    for var in &vars {
        body.push_str(&var.render_ada());
    }
    body.push_str(&format!("end {pkg};\n"));
    Some(ConfigPackage {
        file_name: format!("{}_config.ads", crate_name.to_ascii_lowercase()),
        source: body,
    })
}

/// `usb_embedded` -> `Usb_Embedded_Config`. Each `_`-separated word is
/// capitalized, matching Ada/GNAT package-name convention.
fn ada_config_package_name(crate_name: &str) -> String {
    let cased = crate_name
        .split('_')
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                Some(first) => {
                    first.to_ascii_uppercase().to_string() + &chars.as_str().to_ascii_lowercase()
                }
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join("_");
    format!("{cased}_Config")
}

#[derive(Debug, Clone, PartialEq)]
struct ConfigVar {
    name: String,
    spec: ConfigKind,
}

#[derive(Debug, Clone, PartialEq)]
enum ConfigKind {
    /// Named number — works in both numeric and named-number contexts.
    Number(String),
    Bool(bool),
    Str(String),
    /// `Enum { values, default }` — emit the type + the constant alr would.
    Enum {
        values: Vec<String>,
        default: String,
    },
}

impl ConfigVar {
    fn render_ada(&self) -> String {
        match &self.spec {
            ConfigKind::Number(v) => format!("   {} : constant := {v};\n", self.name),
            ConfigKind::Bool(b) => format!(
                "   {} : constant Boolean := {};\n",
                self.name,
                if *b { "True" } else { "False" }
            ),
            ConfigKind::Str(s) => {
                format!("   {} : constant String := \"{s}\";\n", self.name)
            }
            ConfigKind::Enum { values, default } => {
                let type_name = format!("{}_Kind", self.name);
                let literals = values
                    .iter()
                    .map(|v| sanitize_enum_literal(v))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(
                    "   type {type_name} is ({literals});\n   {} : constant {type_name} := {};\n",
                    self.name,
                    sanitize_enum_literal(default)
                )
            }
        }
    }
}

/// Make a config enum value a legal Ada identifier (alr maps string values to
/// enum literals). Non-identifier chars become `_`; a leading digit is prefixed.
fn sanitize_enum_literal(value: &str) -> String {
    let mut out: String = value
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, 'E');
    }
    if out.is_empty() {
        out.push('E');
    }
    out
}

/// Extract a top-level `key = "value"` string field (e.g. `name`).
fn toml_string_field(text: &str, key: &str) -> Option<String> {
    for raw in text.lines() {
        let line = raw.trim();
        if let Some(rest) = line.strip_prefix(key) {
            let rest = rest.trim_start();
            if let Some(after_eq) = rest.strip_prefix('=') {
                if let Some(v) = first_quoted(after_eq) {
                    return Some(v);
                }
            }
        }
    }
    None
}

/// Parse the `[configuration.variables]` table into typed config variables.
/// Each line is `Name = { type = "...", default = ... }`. A subsequent section
/// header (`[...]`) ends the table.
fn parse_config_variables(text: &str) -> Vec<ConfigVar> {
    let mut out = Vec::new();
    let mut in_section = false;
    for raw in text.lines() {
        let line = strip_inline_comment(raw).trim().to_owned();
        if line.is_empty() {
            continue;
        }
        if line.starts_with('[') {
            in_section =
                line.trim_matches(|c| c == '[' || c == ']').trim() == "configuration.variables";
            continue;
        }
        if !in_section {
            continue;
        }
        let Some((name, rhs)) = line.split_once('=') else {
            continue;
        };
        let name = name.trim();
        if name.is_empty() || !is_ada_identifier(name) {
            continue;
        }
        if let Some(spec) = parse_var_spec(rhs.trim()) {
            out.push(ConfigVar {
                name: name.to_owned(),
                spec,
            });
        }
    }
    out
}

/// Parse `{ type = "Integer", first = 0, default = 256 }` (and Boolean / String
/// / Real / Enum forms) into a `ConfigKind`.
fn parse_var_spec(rhs: &str) -> Option<ConfigKind> {
    let kind = toml_inline_field(rhs, "type")?.to_ascii_lowercase();
    match kind.as_str() {
        "integer" | "real" => {
            let default = toml_inline_bareword(rhs, "default").unwrap_or_else(|| "0".to_owned());
            Some(ConfigKind::Number(default))
        }
        "boolean" => {
            let default =
                toml_inline_bareword(rhs, "default").unwrap_or_else(|| "false".to_owned());
            Some(ConfigKind::Bool(default.eq_ignore_ascii_case("true")))
        }
        "string" => {
            let default = toml_inline_quoted(rhs, "default").unwrap_or_default();
            Some(ConfigKind::Str(default))
        }
        "enum" => {
            let values = toml_inline_string_array(rhs, "values");
            let default = toml_inline_quoted(rhs, "default")
                .or_else(|| values.first().cloned())
                .unwrap_or_default();
            if values.is_empty() {
                None
            } else {
                Some(ConfigKind::Enum { values, default })
            }
        }
        _ => None,
    }
}

/// Value of `key = "..."` inside an inline `{ ... }` table.
fn toml_inline_quoted(table: &str, key: &str) -> Option<String> {
    let pos = find_inline_key(table, key)?;
    first_quoted(&table[pos..])
}

/// Value of `key = "<type>"` — same as quoted, named for clarity at call sites.
fn toml_inline_field(table: &str, key: &str) -> Option<String> {
    toml_inline_quoted(table, key)
}

/// Value of `key = <bareword>` (a number or true/false) inside an inline table.
fn toml_inline_bareword(table: &str, key: &str) -> Option<String> {
    let pos = find_inline_key(table, key)?;
    let rest = table[pos..].trim_start();
    let token: String = rest
        .chars()
        .take_while(|c| {
            c.is_ascii_alphanumeric() || *c == '.' || *c == '-' || *c == '+' || *c == '_'
        })
        .collect();
    (!token.is_empty()).then_some(token)
}

/// Value of `key = ["a", "b"]` inside an inline table.
fn toml_inline_string_array(table: &str, key: &str) -> Vec<String> {
    let Some(pos) = find_inline_key(table, key) else {
        return Vec::new();
    };
    let rest = &table[pos..];
    let Some(open) = rest.find('[') else {
        return Vec::new();
    };
    let Some(close) = rest[open..].find(']') else {
        return Vec::new();
    };
    let inner = &rest[open + 1..open + close];
    let mut out = Vec::new();
    let mut s = inner;
    while let Some(v) = first_quoted(s) {
        let q = s.find('"').unwrap();
        let end = s[q + 1..].find('"').unwrap();
        s = &s[q + 1 + end + 1..];
        out.push(v);
    }
    out
}

/// Byte offset just after the `=` of a whole-word `key =` within an inline
/// table. Whole-word so `default` doesn't match inside another key.
fn find_inline_key(table: &str, key: &str) -> Option<usize> {
    let bytes = table.as_bytes();
    let mut search = 0;
    while let Some(rel) = table[search..].find(key) {
        let at = search + rel;
        let before_ok =
            at == 0 || (!bytes[at - 1].is_ascii_alphanumeric() && bytes[at - 1] != b'_');
        let after = at + key.len();
        let rest = &table[after..];
        let trimmed = rest.trim_start();
        if before_ok && trimmed.starts_with('=') {
            return Some(after + (rest.len() - trimmed.len()) + 1);
        }
        search = after;
    }
    None
}

fn first_quoted(s: &str) -> Option<String> {
    let start = s.find('"')?;
    let end = s[start + 1..].find('"')?;
    Some(s[start + 1..start + 1 + end].to_owned())
}

fn strip_inline_comment(line: &str) -> &str {
    match line.find('#') {
        Some(pos) => &line[..pos],
        None => line,
    }
}

fn is_ada_identifier(s: &str) -> bool {
    let mut chars = s.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_toml(name: &str, body: &str) -> std::path::PathBuf {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let dir = std::env::temp_dir().join(format!("govfuzz-alire-cfg-{name}-{nonce}"));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("alire.toml");
        std::fs::write(&path, body).unwrap();
        path
    }

    #[test]
    fn generates_usb_embedded_config_with_integer_and_boolean_defaults() {
        // usb_embedded's exact [configuration.variables].
        let toml = tmp_toml(
            "usb",
            "name = \"usb_embedded\"\n\
             [[depends-on]]\nhal = \"^1.0.0\"\n\
             [configuration.variables]\n\
             Control_Buffer_Size = {type = \"Integer\", first = 256, default = 256 }\n\
             String_Buffer_Size = {type = \"Integer\", first = 0, default = 256 }\n\
             Max_Strings = {type = \"Integer\", first = 0, default = 10 }\n\
             Log_Verbose = {type = \"Boolean\", default = false }\n",
        );

        let pkg = generate_config_package(&toml).expect("config package generated");

        assert_eq!(pkg.file_name, "usb_embedded_config.ads");
        assert!(
            pkg.source.contains("package Usb_Embedded_Config is"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source
                .contains("Control_Buffer_Size : constant := 256;"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source.contains("String_Buffer_Size : constant := 256;"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source.contains("Max_Strings : constant := 10;"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source
                .contains("Log_Verbose : constant Boolean := False;"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source.contains("end Usb_Embedded_Config;"),
            "{}",
            pkg.source
        );
        let _ = std::fs::remove_dir_all(toml.parent().unwrap());
    }

    #[test]
    fn no_configuration_variables_yields_none() {
        let toml = tmp_toml(
            "plain",
            "name = \"libkeccak\"\n[[depends-on]]\ngnat = \">=11\"\n",
        );
        assert!(generate_config_package(&toml).is_none());
        let _ = std::fs::remove_dir_all(toml.parent().unwrap());
    }

    #[test]
    fn handles_string_and_enum_variables() {
        let toml = tmp_toml(
            "mix",
            "name = \"my_crate\"\n\
             [configuration.variables]\n\
             Greeting = {type = \"String\", default = \"hi\" }\n\
             Mode = {type = \"Enum\", values = [\"fast\", \"safe\"], default = \"safe\" }\n",
        );
        let pkg = generate_config_package(&toml).unwrap();
        assert!(
            pkg.source.contains("Greeting : constant String := \"hi\";"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source.contains("type Mode_Kind is (fast, safe);"),
            "{}",
            pkg.source
        );
        assert!(
            pkg.source.contains("Mode : constant Mode_Kind := safe;"),
            "{}",
            pkg.source
        );
        let _ = std::fs::remove_dir_all(toml.parent().unwrap());
    }
}
