# SPDX-License-Identifier: Apache-2.0

[package]
name = "fake_corba"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "fake_corba"
path = "src/main.rs"

[dev-dependencies]
ada_parser = { path = "../ada_parser" }
