# SPDX-License-Identifier: Apache-2.0

[package]
name = "type_model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "type_model"
path = "src/main.rs"

[dependencies]
c_parser = { path = "../c_parser" }
