# SPDX-License-Identifier: Apache-2.0

[package]
name = "compiler_adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
ada_parser = { path = "../ada_parser" }
libc = "0.2"
regex.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
which.workspace = true

[[bin]]
name = "compiler_adapter"
path = "src/main.rs"
