# SPDX-License-Identifier: Apache-2.0

[package]
name = "govfuzz-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[package.metadata.dist]
dist = true

[package.metadata.dist.binaries]
x86_64-unknown-linux-gnu = ["govfuzz-daemon"]
aarch64-unknown-linux-gnu = ["govfuzz-daemon"]
x86_64-apple-darwin = ["govfuzz-daemon"]
aarch64-apple-darwin = ["govfuzz-daemon"]
x86_64-pc-windows-msvc = ["govfuzz-daemon"]

[dependencies]
ada_parser = { path = "../ada_parser" }
c_parser = { path = "../c_parser" }
cli = { package = "govfuzz", path = "../cli" }
cpp_parser = { path = "../cpp_parser" }
govfuzz_report = { package = "report", path = "../report" }
instrumenter = { path = "../instrumenter" }
serde.workspace = true
serde_json.workspace = true
static_analysis = { path = "../static_analysis" }
target_rank = { path = "../target_rank" }

[lib]
name = "daemon"
path = "src/lib.rs"

[[bin]]
name = "govfuzz-daemon"
path = "src/bin/govfuzz-daemon.rs"

[[bin]]
name = "daemon"
path = "src/main.rs"
