#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

OUT_DIR="dist"
NAME=""
VERSION=""
TARGET_TRIPLE=""
SBOM_CVE_DB=""
BINARY_CVE_DB=""
SEED_DIR=""
SIGN_KEY="govfuzz-dist-root"
SKIP_BUILD=0
DRY_RUN=0
GENERATE_SBOM_CVE_DB=0
GENERATE_BINARY_CVE_DB=0
GENERATE_SEED_DIR=0

usage() {
  cat <<'EOF'
Usage: scripts/package-offline-dist.sh [options]

Build a binary-only GovFuzz distribution tarball. The tarball includes
release binaries, harness runtime support files, a signed content pack,
install.sh, README-DIST.md, RUN-GOVFUZZ.md, and a tiny post-install smoke fixture.
It does not include GovFuzz source.

Options:
  --out DIR               Output directory for the staged dist and tar.gz (default: dist)
  --name NAME             Distribution directory/archive basename
  --version VERSION       Version label for VERSION file and content pack
  --target-triple TRIPLE  Target triple label (default: rustc host triple)
  --sbom-cve-db FILE      GovFuzz SBOM CVE DB JSON to bundle
                          (default: generate dist/content-inputs/sbom-cves.json)
  --binary-cve-db FILE    GovFuzz binary-scan CVE DB JSON to bundle
                          (default: generate dist/content-inputs/binary-cves.json)
  --seed-dir DIR          Seed corpus directory to archive into the content pack
                          (default: generate dist/content-inputs/seeds)
  --sign-key KEY          Update-pack signing key id (default: govfuzz-dist-root)
  --allow-empty-cve-db    Compatibility no-op; omitted DBs are generated by default
  --skip-build            Reuse target/release artifacts instead of cargo build
  --dry-run               Print major actions without executing build/package commands
  -h, --help              Show this help

Build-machine example:
  scripts/package-offline-dist.sh

Destination-machine example:
  tar xzf dist/govfuzz-dist-<version>-<triple>.tar.gz
  cd govfuzz-dist-<version>-<triple>
  ./install.sh
EOF
}

die() {
  printf 'package-offline-dist.sh: %s\n' "$*" >&2
  exit 1
}

quote_cmd() {
  local first=1
  local arg
  for arg in "$@"; do
    if [[ "$first" -eq 0 ]]; then
      printf ' '
    fi
    printf '%q' "$arg"
    first=0
  done
  printf '\n'
}

run() {
  printf '+ '
  quote_cmd "$@"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    "$@"
  fi
}

sanitize_label() {
  printf '%s' "$1" | sed -E 's/[^A-Za-z0-9._-]+/-/g; s/^-+//; s/-+$//'
}

copy_tree() {
  local src="$1"
  local dst="$2"
  [[ -e "$src" ]] || die "missing required path: $src"
  run mkdir -p "$(dirname "$dst")"
  run rm -rf "$dst"
  run cp -a "$src" "$dst"
}

resolve_output_dir() {
  local dir="$1"
  case "$dir" in
    /*) printf '%s' "$dir" ;;
    *) printf '%s/%s' "$REPO_ROOT" "$dir" ;;
  esac
}

write_default_content_inputs() {
  local input_root="$1"
  if [[ "$GENERATE_SBOM_CVE_DB" -eq 1 || "$GENERATE_BINARY_CVE_DB" -eq 1 || "$GENERATE_SEED_DIR" -eq 1 ]]; then
    run mkdir -p "$input_root"
  fi
  if [[ "$GENERATE_SBOM_CVE_DB" -eq 1 ]]; then
    if [[ "$DRY_RUN" -eq 0 && ! -f "$SBOM_CVE_DB" ]]; then
      write_empty_sbom_cve_db "$SBOM_CVE_DB"
    fi
    printf 'SBOM CVE DB: %s\n' "$SBOM_CVE_DB"
  fi
  if [[ "$GENERATE_BINARY_CVE_DB" -eq 1 ]]; then
    if [[ "$DRY_RUN" -eq 0 && ! -f "$BINARY_CVE_DB" ]]; then
      write_empty_binary_cve_db "$BINARY_CVE_DB"
    fi
    printf 'Binary CVE DB: %s\n' "$BINARY_CVE_DB"
  fi
  if [[ "$GENERATE_SEED_DIR" -eq 1 ]]; then
    run mkdir -p "$SEED_DIR"
    printf 'Seed corpus directory: %s\n' "$SEED_DIR"
  fi
}

write_empty_sbom_cve_db() {
  local out="$1"
  cat >"$out" <<'JSON'
{
  "schema_version": "govfuzz.cve_db.v1",
  "vulnerabilities": []
}
JSON
}

write_empty_binary_cve_db() {
  local out="$1"
  cat >"$out" <<'JSON'
{
  "schema_version": "govfuzz.binary.cves.v1",
  "components": []
}
JSON
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out)
      [[ $# -ge 2 ]] || die "--out requires a directory"
      OUT_DIR="$2"
      shift 2
      ;;
    --name)
      [[ $# -ge 2 ]] || die "--name requires a value"
      NAME="$2"
      shift 2
      ;;
    --version)
      [[ $# -ge 2 ]] || die "--version requires a value"
      VERSION="$2"
      shift 2
      ;;
    --target-triple)
      [[ $# -ge 2 ]] || die "--target-triple requires a value"
      TARGET_TRIPLE="$2"
      shift 2
      ;;
    --sbom-cve-db)
      [[ $# -ge 2 ]] || die "--sbom-cve-db requires a file"
      SBOM_CVE_DB="$2"
      shift 2
      ;;
    --binary-cve-db)
      [[ $# -ge 2 ]] || die "--binary-cve-db requires a file"
      BINARY_CVE_DB="$2"
      shift 2
      ;;
    --seed-dir)
      [[ $# -ge 2 ]] || die "--seed-dir requires a directory"
      SEED_DIR="$2"
      shift 2
      ;;
    --sign-key)
      [[ $# -ge 2 ]] || die "--sign-key requires a value"
      SIGN_KEY="$2"
      shift 2
      ;;
    --allow-empty-cve-db)
      shift
      ;;
    --skip-build)
      SKIP_BUILD=1
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown option '$1'"
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd -P)"

if [[ -z "$VERSION" ]]; then
  if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1; then
    VERSION="$(git -C "$REPO_ROOT" describe --tags --always --dirty)"
  else
    VERSION="$(date +%Y%m%d)"
  fi
fi
VERSION="$(sanitize_label "$VERSION")"

if [[ -z "$TARGET_TRIPLE" ]]; then
  TARGET_TRIPLE="$(rustc -vV | awk '/^host:/ {print $2}')"
fi
TARGET_TRIPLE="$(sanitize_label "$TARGET_TRIPLE")"

if [[ -z "$NAME" ]]; then
  NAME="govfuzz-dist-${VERSION}-${TARGET_TRIPLE}"
fi
NAME="$(sanitize_label "$NAME")"

OUT_ROOT="$(resolve_output_dir "$OUT_DIR")"
CONTENT_INPUT_ROOT="$OUT_ROOT/content-inputs"
if [[ -z "$SBOM_CVE_DB" ]]; then
  SBOM_CVE_DB="$CONTENT_INPUT_ROOT/sbom-cves.json"
  GENERATE_SBOM_CVE_DB=1
fi
if [[ -z "$BINARY_CVE_DB" ]]; then
  BINARY_CVE_DB="$CONTENT_INPUT_ROOT/binary-cves.json"
  GENERATE_BINARY_CVE_DB=1
fi
if [[ -z "$SEED_DIR" ]]; then
  SEED_DIR="$CONTENT_INPUT_ROOT/seeds"
  GENERATE_SEED_DIR=1
fi

write_default_content_inputs "$CONTENT_INPUT_ROOT"

if [[ -n "$SBOM_CVE_DB" && ! -f "$SBOM_CVE_DB" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_SBOM_CVE_DB" -eq 0 ]]; then
    die "--sbom-cve-db file not found: $SBOM_CVE_DB"
  fi
fi
if [[ -n "$BINARY_CVE_DB" && ! -f "$BINARY_CVE_DB" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_BINARY_CVE_DB" -eq 0 ]]; then
    die "--binary-cve-db file not found: $BINARY_CVE_DB"
  fi
fi
if [[ -n "$SEED_DIR" && ! -d "$SEED_DIR" ]]; then
  if [[ "$DRY_RUN" -eq 0 || "$GENERATE_SEED_DIR" -eq 0 ]]; then
    die "--seed-dir directory not found: $SEED_DIR"
  fi
fi

cd "$REPO_ROOT"

if [[ "$SKIP_BUILD" -eq 0 ]]; then
  run cargo build --release --workspace
fi

TARGET_DIR="$REPO_ROOT/target/release"
GOVFUZZ_BIN="$TARGET_DIR/govfuzz"
DAEMON_BIN="$TARGET_DIR/govfuzz-daemon"
SHIM_DIST="$TARGET_DIR/libgovfuzz_runtrace.so"
SHIM_CANONICAL="$TARGET_DIR/libgovfuzz_runtrace_shim.so"

if [[ "$DRY_RUN" -eq 0 ]]; then
  [[ -x "$GOVFUZZ_BIN" ]] || die "missing release binary: $GOVFUZZ_BIN"
  [[ -x "$DAEMON_BIN" ]] || die "missing release binary: $DAEMON_BIN"
  if [[ ! -f "$SHIM_DIST" && ! -f "$SHIM_CANONICAL" ]]; then
    die "missing runtrace shim beside release binaries"
  fi
fi

STAGE_ROOT="$OUT_ROOT/$NAME"
TOOL_DIR="$STAGE_ROOT/tool"
CONTENT_ROOT="$STAGE_ROOT/content"
PACK_ROOT="$CONTENT_ROOT/packs/current"
TARBALL="$OUT_ROOT/${NAME}.tar.gz"

run rm -rf "$STAGE_ROOT"
run mkdir -p "$TOOL_DIR" "$PACK_ROOT/rules" "$PACK_ROOT/cve" "$PACK_ROOT/corpus"

run cp "$GOVFUZZ_BIN" "$TOOL_DIR/govfuzz"
run cp "$DAEMON_BIN" "$TOOL_DIR/govfuzz-daemon"
if [[ -f "$SHIM_DIST" ]]; then
  run cp "$SHIM_DIST" "$TOOL_DIR/libgovfuzz_runtrace.so"
fi
if [[ -f "$SHIM_CANONICAL" ]]; then
  run cp "$SHIM_CANONICAL" "$TOOL_DIR/libgovfuzz_runtrace_shim.so"
fi

copy_tree "$REPO_ROOT/c_runtime" "$TOOL_DIR/c_runtime"
copy_tree "$REPO_ROOT/ada_runtime" "$TOOL_DIR/ada_runtime"
run rm -rf "$TOOL_DIR/ada_runtime/obj" "$TOOL_DIR/ada_runtime/lib"
run find "$TOOL_DIR/ada_runtime" -type f \( -name '*.o' -o -name '*.ali' -o -name '*.stdout' -o -name '*.stderr' -o -name '*.lexch' \) -delete
copy_tree "$REPO_ROOT/java_runtime" "$TOOL_DIR/java_runtime"
copy_tree "$REPO_ROOT/python_runtime" "$TOOL_DIR/python_runtime"
run find "$TOOL_DIR/python_runtime" -type d -name __pycache__ -prune -exec rm -rf {} +
copy_tree "$REPO_ROOT/perl_runtime" "$TOOL_DIR/perl_runtime"
copy_tree "$REPO_ROOT/crates/rust_runtime" "$TOOL_DIR/crates/rust_runtime"
copy_tree "$REPO_ROOT/csharp_runtime" "$TOOL_DIR/csharp_runtime"
copy_tree "$REPO_ROOT/js_runtime" "$TOOL_DIR/js_runtime"
copy_tree "$REPO_ROOT/ruby_runtime" "$TOOL_DIR/ruby_runtime"
copy_tree "$REPO_ROOT/lua_runtime" "$TOOL_DIR/lua_runtime"
copy_tree "$REPO_ROOT/php_runtime" "$TOOL_DIR/php_runtime"

run cp "$SCRIPT_DIR/install-dist.sh" "$STAGE_ROOT/install.sh"
run chmod +x "$STAGE_ROOT/install.sh"
run cp "$REPO_ROOT/docs/site/offline-auto-runbook.md" "$STAGE_ROOT/AUTO-OFFLINE-RUNBOOK.md"
run mkdir -p "$TOOL_DIR/docs"
run cp "$REPO_ROOT/docs/site/offline-auto-runbook.md" "$TOOL_DIR/docs/AUTO-OFFLINE-RUNBOOK.md"

run mkdir -p "$STAGE_ROOT/smoke/c"
if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$STAGE_ROOT/smoke/c/govfuzz_smoke.c" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
#include <stddef.h>

int govfuzz_smoke_parse(const unsigned char *data, size_t len) {
    if (len >= 4 && data[0] == 'G' && data[1] == 'F' && data[2] == 'Z') {
        return data[3] == '!';
    }
    return 0;
}
EOF
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$STAGE_ROOT/VERSION" <<EOF
name=$NAME
version=$VERSION
target_triple=$TARGET_TRIPLE
built_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)
commit=$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || printf unknown)
EOF

  cat >"$STAGE_ROOT/README-DIST.md" <<'EOF'
# GovFuzz Distribution

This package contains GovFuzz release binaries, harness runtime support files,
a tiny post-install smoke fixture, and a signed content pack.

Install or update:

```sh
./install.sh
```

Re-running `install.sh` from a newer package **updates** an existing install in
place — you do not uninstall first. It is idempotent and data-safe: it stages the
new files, then atomically swaps them in. It **replaces** the binaries + runtime
trees, **preserves** your `<prefix>/packs/` and `<prefix>/corpora/`, and **backs
up** the previous install to `<prefix>.backup.<timestamp>` (roll back with `mv`).
Your run outputs under any `--work-dir` live outside the prefix and are never
touched.

The installer can also be run non-interactively:

```sh
./install.sh --non-interactive [options]
```

Installer options:

```text
--prefix DIR            Install prefix (default: /opt/govfuzz)
--bin-dir DIR           Directory for govfuzz symlinks (default: /usr/local/bin)
--non-interactive       Do not prompt; use selected or default profiles
--languages LIST        Comma list: c,cpp,rust,java,python,perl,go,ada,cobol,
                        fortran,csharp,javascript,typescript,ruby,lua,php,all,none
--targets LIST          Comma list: native,windows,aarch64,all,none
--fuzzers LIST          Comma list: builtin,afl,all,none
--extras LIST           Comma list: build-recovery,sandbox,archives,all,none
--install-seeds         Extract bundled seed corpus into <prefix>/corpora/seeds
--package-manager NAME  System package manager: auto, apt-get, dnf, yum, none
                        (default: auto)
--no-system-packages    Skip system package installation
--no-apt                Compatibility alias for --no-system-packages
--no-rustup             Skip rustup installation and nightly toolchain setup
--no-content            Skip signed content pack verify/install
--no-symlink            Do not create govfuzz symlinks in --bin-dir
--no-smoke              Skip the post-install govfuzz auto smoke test
--smoke-work-dir DIR    Work directory for the post-install smoke test
--dry-run               Print commands without executing them
-h, --help              Show installer help
```

Multiple-selection example:

```sh
./install.sh --non-interactive \
  --prefix /opt/govfuzz \
  --languages c,cpp,rust \
  --targets native,aarch64 \
  --fuzzers builtin,afl \
  --extras build-recovery,archives
```

Full install example:

```sh
./install.sh --non-interactive \
  --languages all \
  --targets all \
  --fuzzers all \
  --extras all \
  --install-seeds
```

`--languages all` means all sixteen fuzzing lanes. With no language option, the
installer keeps the original eight core lanes selected and offers COBOL,
Fortran, C#, JavaScript, TypeScript, Ruby, Lua, and PHP as opt-ins. The C# lane
requires a separately staged .NET 8 SDK and `SharpFuzz.CommandLine`; TypeScript
requires `esbuild` on `PATH` or already installed in the target project.

The installer detects Debian/Ubuntu (`apt-get`) and RHEL-family
(`dnf`/`yum`) hosts automatically. On RHEL, packages absent from the enabled
repositories are reported per lane while available core dependencies continue
to install. Use `--package-manager` to override detection.

The bundled content pack lives under `content/packs/current` and is verified
before install.

If GovFuzz itself errors on your source tree (an internal panic, or a harness its
own codegen left broken), it records a boiled-down bug report at
`<work-dir>/auto/bug-report.md` (+ `.json`) instead of only crashing, and keeps
sweeping past the bad file. Run with `--debug` to capture a backtrace per panic:

```sh
govfuzz auto --debug <source-tree> --work-dir govfuzz_work
```

Send `bug-report.md` (or one entry from it) to the maintainer — it carries the
govfuzz version/commit, the file/target, and the backtrace needed to fix it.

For running GovFuzz after installation, see `RUN-GOVFUZZ.md`. For the strongest
offline Ada/C/C++ recovery commands, including known-build, unknown-build, and
forced fallback variants, see `AUTO-OFFLINE-RUNBOOK.md`. The installer also
places that runbook at `<prefix>/docs/AUTO-OFFLINE-RUNBOOK.md`.
EOF

  cat >"$STAGE_ROOT/RUN-GOVFUZZ.md" <<'EOF'
<!-- SPDX-License-Identifier: Apache-2.0 -->

# Running GovFuzz

This guide is for operators using this binary-only GovFuzz distribution after
`install.sh` has installed it.

## Installed Layout

The default install prefix is `/opt/govfuzz`. Unless you passed different
installer options, the installer copies the CLI, daemon, runtrace shim, and
harness runtime files there, then creates `govfuzz` and `govfuzz-daemon`
symlinks in `/usr/local/bin`.

Useful locations:

- `/opt/govfuzz/govfuzz` - CLI binary
- `/opt/govfuzz/govfuzz-daemon` - JSON-RPC/read-only-MCP daemon for IDE and agent integrations
- `/opt/govfuzz/libgovfuzz_runtrace.so` - LD_PRELOAD runtime shim
- `/opt/govfuzz/packs/` - installed signed offline content packs
- `/opt/govfuzz/corpora/seeds/` - bundled seeds when installed with
  `--install-seeds`
- `VERSION` - package name, version, target triple, build time, and commit

Run this first:

```sh
govfuzz --help
```

If you installed without symlinks, call `/opt/govfuzz/govfuzz` directly or add
`/opt/govfuzz` to `PATH`.

## Smoke Test

The installer runs the bundled C smoke fixture by default. To rerun it from the
extracted distribution directory:

```sh
# --per-target-time is in seconds; 5 means 5 seconds per discovered target.
govfuzz auto smoke/c --work-dir /tmp/govfuzz-smoke --per-target-time 5 --verbose
```

The smoke run proves discovery, harness generation, build, fuzz execution, and
report rendering for the C lane. It requires `clang` and `make`.

## Run an Automatic Sweep

For most source drops, use `govfuzz auto`. It discovers targets, ranks them,
generates harnesses, repairs build gaps where possible, fuzzes, and writes
reports:

```sh
# --per-target-time is in seconds; 30 means 30 seconds per discovered target.
govfuzz auto /path/to/source-tree \
  --work-dir govfuzz_work \
  --per-target-time 30 \
  --verbose
```

`auto` recognizes all sixteen source lanes: Ada, C, C++, Rust, Java, Python,
Perl, Go, COBOL, Fortran, C#, JavaScript, TypeScript, Ruby, Lua, and PHP.

Useful options:

- `--languages c,cpp,ada,csharp,javascript` limits the sweep to selected lanes;
  omit it to use every lane found in the tree.
- `--max-targets 25` runs only the highest ranked targets.
- `--campaign-time 3600` caps the whole run at 3600 seconds, which is one hour.
  This is the whole-campaign maximum time; use it when you want the sweep to
  stop starting new targets after a fixed wall-clock budget.
- `--target NAME`, `--harness-id ID`, or `--target-file PATH` reruns a narrower
  slice.
- `--engine builtin,afl++` runs both engines for native C/C++ targets when AFL++
  is installed.
- `--sbom` writes SBOM, CycloneDX, vulnerability, VEX, and CSV artifacts at the
  end of the sweep.
- `--debug` captures a backtrace for any govfuzz-internal panic and enriches the
  bug report (see "When GovFuzz itself errors" below).

Missing language toolchains are reported as skipped or failed build lanes; they
do not require network access. Install only the toolchains for the languages you
intend to fuzz.

For broken or incomplete Ada/C/C++ source drops, see
`AUTO-OFFLINE-RUNBOOK.md` in this distribution. It gives the strongest
known-build and unknown-build commands, explains which recovery flags combine,
and keeps the `--force` fallback in a separate evidence bucket. After install,
the same file is available at `/opt/govfuzz/docs/AUTO-OFFLINE-RUNBOOK.md` when
the default prefix is used.

## Read Results

The main outputs are under the work directory:

- `auto/summary.txt` - outcome summary, throughput, coverage, and artifact paths
- `auto/run.md` - human-readable report
- `auto/run.json` - machine-readable report
- `auto/bug-report.md` / `auto/bug-report.json` - GovFuzz's OWN internal defects,
  written only when GovFuzz itself panicked or a codegen bug occurred (see below)
- `findings/` - saved crashing or policy-relevant test cases
- `harnesses/` and `build/` - generated harnesses and compiled outputs
- `sbom/` - supply-chain outputs when `--sbom` is used

Start with:

```sh
less govfuzz_work/auto/run.md
```

Use `auto/run.json` for CI ingestion, dashboards, and repeatable triage.

## When GovFuzz itself errors: `--debug` and the bug report

If GovFuzz *itself* fails on your tree — an internal panic, or a harness its own
codegen left broken — it records that as a bug report instead of only crashing,
and keeps sweeping past the bad file. This is distinct from findings (bugs in
your target) and from `missing-deps.txt` (dependencies your environment lacks):
the bug report is GovFuzz's OWN defects, boiled down to what a maintainer needs.

- A GovFuzz-internal panic while parsing or fuzzing ONE file is caught at that
  file/target boundary — the run records it and continues instead of aborting.
- When a run hits any internal defect, GovFuzz writes
  `<work-dir>/auto/bug-report.json` and `bug-report.md` and prints a one-line
  pointer. A clean run writes neither.

Add `--debug` to capture a backtrace per panic (it sets `RUST_BACKTRACE` for
you), which pins the exact source line:

```sh
govfuzz auto --debug /path/to/source-tree --work-dir govfuzz_work
# → govfuzz_work/auto/bug-report.md
```

`bug-report.md` lists each issue with its category (`PANIC` / `codegen`), the
source file and target, the language, the GovFuzz version + commit, and (under
`--debug`) the backtrace. Send that file — or a single entry — to get the defect
fixed; it carries everything needed to reproduce.

## Updating this install (data-safe)

Re-running `install.sh` from a newer package updates this install in place; you
do not uninstall first. It is idempotent and never destroys data: it **replaces**
the binaries + runtime trees, **preserves** `<prefix>/packs/` and
`<prefix>/corpora/`, and **backs up** the previous install to
`<prefix>.backup.<timestamp>` (roll back with `mv`). Your run outputs under any
`--work-dir` live outside the prefix and are never touched. See `README-DIST.md`
for the full update walkthrough.

## Generate Reports and CSV

`govfuzz auto` writes the primary run report automatically:

- `govfuzz_work/auto/run.md` - human-readable campaign report
- `govfuzz_work/auto/run.json` - machine-readable campaign report
- `govfuzz_work/auto/findings.csv` - one row per root-cause finding group

To render a separate findings report bundle from saved findings, use
`govfuzz report`. This is useful when you want spreadsheet, SARIF, or JUnit
outputs for triage, CI, or compliance systems:

```sh
govfuzz report \
  --findings govfuzz_work/findings \
  --out govfuzz_work/reports \
  --run last \
  --csv \
  --sarif \
  --junit
```

That command writes:

- `govfuzz_work/reports/last.md`
- `govfuzz_work/reports/last.json`
- `govfuzz_work/reports/last.csv`
- `govfuzz_work/reports/last.sarif`
- `govfuzz_work/reports/last.junit.xml`

For supply-chain reporting, `govfuzz auto --sbom` writes SBOM artifacts at the
end of the sweep. You can also generate them directly from a source tree or work
directory:

```sh
govfuzz sbom /path/to/source-tree \
  --out govfuzz_work/sbom \
  --emit sbom,cyclonedx,vulnerabilities,openvex,csv
```

That command writes JSON SBOM/VEX/vulnerability artifacts plus CSV projections:

- `govfuzz_work/sbom/sbom.json`
- `govfuzz_work/sbom/cyclonedx.json`
- `govfuzz_work/sbom/vulnerabilities.json`
- `govfuzz_work/sbom/openvex.json`
- `govfuzz_work/sbom/sbom.csv`
- `govfuzz_work/sbom/vulnerabilities.csv`

If you installed a real offline CVE database in a content pack, pass it with
`--vuln-db /opt/govfuzz/packs/<pack-id>/cve/sbom-cves.json`. Without a CVE
database, SBOM inventory still works, but vulnerability match outputs are empty.

## Fuzz and Replay a Specific Harness

`govfuzz auto` is the normal entry point, but you can continue fuzzing a built
harness directly:

```sh
# --time accepts duration suffixes; 10m means 10 minutes.
govfuzz fuzz govfuzz_work --harness H-EXAMPLE --time 10m --seed-input smoke
```

Replay a finding from a report:

```sh
govfuzz replay --finding govfuzz_work/findings/F-0001
```

If automatic harness resolution cannot find the binary, pass it explicitly:

```sh
govfuzz replay --finding govfuzz_work/findings/F-0001 \
  --harness govfuzz_work/build/H-EXAMPLE/main
```

## Runtime Shim

The shim is armed for native Ada, C, C++, Rust, Go, COBOL, and Fortran runs plus
Python, Perl, Ruby, Lua, and PHP interpreter processes. If the CLI cannot find
the shim automatically, point it at the installed copy:

```sh
export GOVFUZZ_RUNTRACE_SHIM=/opt/govfuzz/libgovfuzz_runtrace.so
```

Java, C#, JavaScript, and TypeScript fuzzing do not load the LD_PRELOAD shim
because interposing their managed runtime processes would mostly observe the
launcher/runtime rather than target behavior. Cross-compiled and emulated runs
also leave it disabled.

## Daemon and IDE Use

`govfuzz-daemon` is installed for IDE thin clients, JSON-RPC integrations, and
five read-only MCP tools. Run the daemon from the installed prefix or through
the symlink configured by the installer:

```sh
govfuzz-daemon
# MCP stdio transport for an approved local agent host:
govfuzz-daemon --mcp
```

Use the CLI for batch and CI jobs. Use default daemon mode when an editor owns
GovFuzz sessions, or `--mcp` for read-only static scan, target ranking, harness
preflight, report summary, and finding lookup. MCP does not build or fuzz.

## Offline Content

The installer verifies and installs the signed content pack from
`content/packs/current`. Installed packs live under `/opt/govfuzz/packs/`.

A content pack is a signed offline bundle of GovFuzz data. This distribution
uses it for the built-in rule catalog, offline CVE databases, and optional seed
corpora. Bundle a content pack when the destination machine cannot fetch updates
from the network, when you need a repeatable evidence trail for exactly which
rules and vulnerability data were used, or when you want to move customer- or
program-specific corpora through the same verified install path as the tool.

To inspect or verify a pack manually:

```sh
govfuzz pack verify content/packs/current/update-pack.json \
  --root content/packs/current \
  --policy content/govfuzz-policy.json
```

If you installed bundled seeds with `--install-seeds`, pass them into a run with:

Seeds are example input files that initialize the fuzz corpus before mutation
starts. Good seeds are valid or nearly-valid messages, files, packets, records,
or API payloads for the target parser. Installing seeds is useful because it can
reach format gates faster, preserve known-good regression inputs, and share a
common starting corpus across offline machines.

```sh
govfuzz auto /path/to/source-tree \
  --work-dir govfuzz_work \
  --seed-dir /opt/govfuzz/corpora/seeds
```
EOF
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  "$GOVFUZZ_BIN" rules list --json >"$PACK_ROOT/rules/static.json"
  cp "$SBOM_CVE_DB" "$PACK_ROOT/cve/sbom-cves.json"
  cp "$BINARY_CVE_DB" "$PACK_ROOT/cve/binary-cves.json"
  tar -C "$SEED_DIR" -czf "$PACK_ROOT/corpus/seeds.tar.gz" .
fi

if [[ "$DRY_RUN" -eq 0 ]]; then
  cat >"$CONTENT_ROOT/govfuzz-policy.json" <<EOF
{
  "schema_version": "govfuzz.policy.v1",
  "policy_id": "govfuzz-dist",
  "version": "$VERSION",
  "rules": {
    "enabled": [],
    "disabled": []
  },
  "update_packs": {
    "allowed_kinds": ["rules", "cve", "corpus"],
    "require_signature": true,
    "trusted_keys": ["$SIGN_KEY"]
  }
}
EOF
fi

PACK_ID="govfuzz-content-$VERSION"
run "$GOVFUZZ_BIN" pack create \
  --root "$PACK_ROOT" \
  --pack-id "$PACK_ID" \
  --version "$VERSION" \
  --item rules:rules/static.json \
  --item cve:cve/sbom-cves.json \
  --item cve:cve/binary-cves.json \
  --item corpus:corpus/seeds.tar.gz \
  --sign-key "$SIGN_KEY" \
  --out "$PACK_ROOT/update-pack.json"

run "$GOVFUZZ_BIN" pack verify "$PACK_ROOT/update-pack.json" \
  --root "$PACK_ROOT" \
  --policy "$CONTENT_ROOT/govfuzz-policy.json"

run tar -C "$OUT_ROOT" -czf "$TARBALL" "$NAME"
run sha256sum "$TARBALL"
if [[ "$DRY_RUN" -eq 0 ]]; then
  (cd "$OUT_ROOT" && sha256sum "${NAME}.tar.gz" >"${NAME}.tar.gz.sha256")
fi

printf 'Distribution archive: %s\n' "$TARBALL"
printf 'Checksum: %s.sha256\n' "$TARBALL"
